openapi: 3.0.3
info:
  title: Pricing API
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /product-price:
    get:
      summary: Get price by date, productId and brandId
      parameters:
        - in: query
          name: date
          required: true
          schema:
            type: string
            format: date-time
        - in: query
          name: productId
          required: true
          schema:
            type: integer
            format: int64
        - in: query
          name: brandId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Price found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceDto'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    PriceDto:
      type: object
      properties:
        productId:
          type: integer
          format: int64
        brandId:
          type: integer
          format: int64
        priceList:
          type: integer
          format: int64
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        value:
          type: number
          format: double
        currency:
          type: string
      required: [productId, brandId, priceList, startDate, endDate, value, currency]
    ErrorResponse:
      type: object
      properties:
        status:
          type: integer
        message:
          type: string
      required: [status, message]
